# Generated by Django 4.1.2 on 2022-10-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "lighting_talks_scheduler",
            "0002_alter_person_email_alter_person_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="confirm_your_email_address",
            field=models.EmailField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
