# Generated by Django 4.0.6 on 2022-10-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighting_talks_scheduler', '0003_person_confirm_your_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightningtalk',
            name='date',
        ),
        migrations.AddField(
            model_name='lightningtalk',
            name='day',
            field=models.IntegerField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lightningtalk',
            name='month',
            field=models.IntegerField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lightningtalk',
            name='year',
            field=models.IntegerField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
